# Generated by Django 3.0.2 on 2020-02-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=55)),
                ('info', models.CharField(max_length=255)),
                ('discount', models.FloatField()),
            ],
        ),
    ]
